from django.conf.urls.defaults import patterns,include
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/',include(admin.site.urls)), 
    (r'^recruit_index/$','recruitment.views.recruit_index'),
    (r'^check_location/$','recruitment.views.check_location'),
    (r'^check_title/$','recruitment.views.check_title'),
    (r'^check_skill_set/$','recruitment.views.check_skill_set'),
    (r'^check_roles/$','recruitment.views.check_roles'),
    (r'^check_referral/$','recruitment.views.check_referral'),
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^create_user/$','recruitment.views.create_user'),
    (r'^create_login/$','recruitment.views.create_login'),
    (r'^check_email/$','recruitment.views.check_email'),
    (r'^check_contact_number/$','recruitment.views.check_contact_number'),
    (r'^checkusername/$','recruitment.views.checkusername'),
    (r'^all_users/$','recruitment.views.all_users'),
    (r'^enter_feedback/$','recruitment.views.enter_feedback'),
    (r'^feedback_updated/$','recruitment.views.feedback_updated'),
    (r'^check_feedback/$','recruitment.views.check_feedback'),
    (r'^viewable_feedback/$','recruitment.views.viewable_feedback'),
    (r'^viewable_HRfeedback/$','recruitment.views.viewable_HRfeedback'),
    (r'^hr_feedback_update/$','recruitment.views.hr_feedback_update'),
    (r'^hr_feedback_updated/$','recruitment.views.hr_feedback_updated'),
    (r'^check_passport_number/$','recruitment.views.check_passport_number'),
    (r'^update_resume/$','recruitment.views.update_resume'),
    (r'^update_resume_done/$','recruitment.views.update_resume_done'),
    (r'^submit/$','recruitment.views.submit_recruit_form'),
    (r'^candidate_added/$','recruitment.views.candidate_added'),
    (r'^submit_candidate/$','recruitment.views.submit_candidate_form'),
    (r'^add_job/$','recruitment.views.add_job'),
    (r'^update_job/$','recruitment.views.update_job'),
    (r'^job_update_done/$','recruitment.views.job_update_done'),
    (r'^add_candidate/$','recruitment.views.add_candidate'),
    (r'^update_candidate_detail/$','recruitment.views.update_candidate_detail'),
    (r'^candidate_update_done/$','recruitment.views.candidate_update_done'),
)
